/** Common countries for Uzbek/CIS family trees, Uzbekistan and its neighbors first. Not
 * an exhaustive ISO list — the field is a free-text-capable combobox, so anything not
 * listed can still be typed in directly. */
export const COUNTRIES = [
  "Oʻzbekiston",
  "Qozogʻiston",
  "Qirgʻiziston",
  "Tojikiston",
  "Turkmaniston",
  "Rossiya",
  "Ukraina",
  "Belarus",
  "Ozarbayjon",
  "Armaniston",
  "Gruziya",
  "Moldova",
  "Xitoy",
  "Turkiya",
  "Eron",
  "Afgʻoniston",
  "Pokiston",
  "Hindiston",
  "Saudiya Arabistoni",
  "Birlashgan Arab Amirliklari",
  "Qatar",
  "Koreya Respublikasi",
  "Yaponiya",
  "Germaniya",
  "Fransiya",
  "Buyuk Britaniya",
  "Italiya",
  "Ispaniya",
  "Polsha",
  "Chexiya",
  "Niderlandiya",
  "Shvetsiya",
  "Norvegiya",
  "Finlyandiya",
  "Amerika Qoʻshma Shtatlari",
  "Kanada",
  "Avstraliya",
  "Isroil",
  "Misr",
];
